language: rust
os:
  - linux
  - osx
rust:
  - stable
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
dist: xenial
env:
  - RUST_BACKTRACE=1
addons:
  apt:
    packages:
      - libxcb-shm0-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
      - libxv-dev
      - libx11-xcb-dev
      - libncurses5-dev
      - libgoogle-perftools-dev
      - libncursesw5-dev
