language: rust
os:
  - linux
  - osx
rust:
  - stable
  - nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
dist: xenial
addons:
  apt:
    packages:
      - libx11-xcb-dev
      - libncurses5-dev
      - libgoogle-perftools-dev
      - libncursesw5-dev
